(function() {
    var option = {};
    option.allBlocks = function() {
        return [{
            category: "start",
            blocks: [
                "when_run_button_click",
                "when_some_key_pressed",
                "mouse_clicked",
                "mouse_click_cancled",
                "when_object_click",
                "when_message_cast",
                "message_cast",
            ]
        }, {
            category: "flow",
            blocks: [
                "wait_second",
                "repeat_basic",
                "repeat_inf",
                "repeat_while_true",
                "stop_repeat",
                "_if",
                "if_else",
                "wait_until_true",
            ]
        }, {
            category: "moving",
            blocks: [
                "move_direction",
                "bounce_wall",
                "move_x",
                "move_y",
                "locate_y",
                "locate_xy",
                "locate_xy_time",
                "locate",
                "locate_object_time",
                "rotate_relative",
                "direction_relative",
                "rotate_absolute",
                "direction_absolute",
                "see_angle_object",
            ]
        }, {
            category: "looks",
            blocks: [
                "show",
                "hide",
                "dialog_time",
                "change_to_some_shape",
                "change_to_next_shape",
                "add_effect_amount",
                "change_effect_amount",
                "erase_all_effects",
                "change_scale_size",
                "set_scale_size",
            ]
        }, {
            category: "brush",
            blocks: [
                "brush_stamp",
                "start_drawing",
                "stop_drawing",
                "set_color",
                "change_thickness",
                "set_thickness",
                "brush_erase_all"
            ]
        }, {
            category: "text",
            blocks: [
                "text_write",
                "text_append",
                "text_prepend",
                "text_flush"
            ]
        }, {
            category: "sound",
            blocks: [
                "sound_something_with_block",
                "sound_something_wait_with_block",
                "sound_volume_change",
                "sound_volume_set",
            ]
        }, {
            category: "judgement",
            blocks: [
                "is_clicked",
                "is_press_some_key",
                "reach_something",
                "boolean_basic_operator",
            ]
        }, {
            category: "calc",
            blocks: [
                "calc_basic",
                "calc_rand",
                "coordinate_object",
                "quotient_and_mod",
                "get_project_timer_value",
                "choose_project_timer_action",
                "set_visible_project_timer",
                "length_of_string",
                "combine_something",
                "char_at",
                "substring",
                "replace_string",
            ]
        }, {
            category: "variable",
            blocks: [
                "variableAddButton",
                "ask_and_wait",
                "get_canvas_input_value",
                "set_visible_answer",
                "get_variable",
                "change_variable",
                "set_variable",
                "show_variable",
                "hide_variable",
            ]
        }, {
            category: "hw_motor",
            visible: false,
            blocks: [
                "practical_arts_move_for_secs",
                "practical_arts_move_for",
                "practical_arts_stop_for",
                "practical_arts_set_servo2",
            ]
        }, {
            category: "hw_melody",
            visible: false,
            blocks: [
                "practical_arts_melody_note_for",
            ]
        }, {
            category: "hw_sensor",
            visible: false,
            blocks: [
                "practical_arts_touch_value",
                "practical_arts_touch_value_boolean",
                "practical_arts_light_value",
                "practical_arts_light_value_boolean",
                "practical_arts_sound_value",
                "practical_arts_sound_value_boolean",
                "practical_arts_irs_value",
                "practical_arts_irs_value_boolean",
            ]
        }, {
            category: "hw_led",
            visible: false,
            blocks: [
                "practical_arts_diode_secs_toggle",
                "practical_arts_diode_toggle",
                "practical_arts_diode_inout_toggle",
                "practical_arts_diode_set_output",
                "practical_arts_diode_input_value"
            ]
        }, {
            category: "hw_robot",
            blocks: [
                "arduino_download_connector",
                "download_guide",
                "arduino_download_source",
                "arduino_connected",
                "arduino_reconnect",
                // "arduino_open",
                // "arduino_get_number_sensor_value",
                // "arduino_get_digital_value",
                // "arduino_toggle_led",
                // "arduino_toggle_pwm",
                // "arduino_convert_scale",
                // //arduinoExt
                // "arduino_ext_get_analog_value",
                // "arduino_ext_get_ultrasonic_value",
                // "arduino_ext_get_digital",
                // "arduino_ext_toggle_led",
                // "arduino_ext_digital_pwm",
                // "arduino_ext_set_servo",
                // "arduino_ext_set_tone",
                // //joystick
                // "joystick_get_number_sensor_value",
                // "joystick_get_digital_value",
                // "joystick_toggle_led",
                // "joystick_toggle_pwm",
                // "joystick_convert_scale",
                // //dplay
                // "dplay_get_number_sensor_value",
                // "dplay_get_value",
                // "dplay_get_gas_sensor_value",
                // "dplay_get_dust_sensor_value",
                // "dplay_get_CO2_sensor_value",
                // "dplay_convert_scale",
                // "dplay_get_digital_value",
                // "dplay_get_switch_status",
                // "dplay_get_tilt",
                // "dplay_toggle_led",
                // "dplay_toggle_pwm",
                // "dplay_select_led",
                // "dplay_DCmotor",
                // "dplay_DCmotor_speed",
                // "dplay_buzzer",
                // "dplay_servo",
                // "dplay_Robot_run",
                // "dplay_Robot_run_sec",
                // "dplay_robot_speed_sel",
                // "dplay_robot_speed_set",
                // "dplay_robot_stop",
                // //nemoino
                // "nemoino_get_named_sensor_value",
                // "nemoino_get_sound_status",
                // "nemoino_is_button_pressed",
                // "nemoino_get_accelerometer_direction",
                // "nemoino_get_accelerometer_value",
                // "nemoino_get_number_sensor_value",
                // "nemoino_get_digital_value",
                // "nemoino_toggle_led",
                // "nemoino_toggle_pwm",
                // "nemoino_convert_scale",
                // //neobot
                // "neobot_sensor_value",
                // "neobot_sensor_convert_scale",
                // "neobot_left_motor",
                // "neobot_stop_left_motor",
                // "neobot_right_motor",
                // "neobot_stop_right_motor",
                // "neobot_all_motor",
                // "neobot_stop_all_motor",
                // "neobot_set_servo",
                // "neobot_set_output",
                // "neobot_set_fnd",
                // "neobot_set_fnd_off",
                // "neobot_play_note_for",
                // "bitbrick_sensor_value",
                // "bitbrick_convert_scale",
                // "bitbrick_is_touch_pressed",
                // "bitbrick_turn_off_color_led",
                // "bitbrick_turn_on_color_led_by_rgb",
                // "bitbrick_turn_on_color_led_by_picker",
                // "bitbrick_turn_on_color_led_by_value",
                // "bitbrick_buzzer",
                // "bitbrick_turn_off_all_motors",
                // "bitbrick_dc_speed",
                // "bitbrick_dc_direction_speed",
                // "bitbrick_servomotor_angle",
                // "cobl_read_ultrason",
                // "cobl_read_potenmeter",
                // "cobl_read_irread1",
                // "cobl_read_irread2",
                // "cobl_read_joyx",
                // "cobl_read_joyy",
                // //"cobl_read_sens1",
                // //"cobl_read_sens2",
                // "cobl_read_tilt",
                // "cobl_read_temps",
                // "cobl_read_light",
                // "cobl_read_btn",
                // "cobl_led_control",
                // "cobl_servo_angle_control",
                // "cobl_melody",
                // "cobl_dcmotor",
                // "cobl_extention_port",
                // "cobl_external_led",
                // "cobl_7_segment",
                // "hamster_hand_found",
                // "hamster_value",
                // "hamster_move_forward_once",
                // "hamster_turn_once",
                // "hamster_move_forward_for_secs",
                // "hamster_move_backward_for_secs",
                // "hamster_turn_for_secs",
                // "hamster_change_both_wheels_by",
                // "hamster_set_both_wheels_to",
                // "hamster_change_wheel_by",
                // "hamster_set_wheel_to",
                // "hamster_follow_line_using",
                // "hamster_follow_line_until",
                // "hamster_set_following_speed_to",
                // "hamster_stop",
                // "hamster_set_led_to",
                // "hamster_clear_led",
                // "hamster_beep",
                // "hamster_change_buzzer_by",
                // "hamster_set_buzzer_to",
                // "hamster_clear_buzzer",
                // "hamster_play_note_for",
                // "hamster_rest_for",
                // "hamster_change_tempo_by",
                // "hamster_set_tempo_to",
                // "hamster_set_port_to",
                // "hamster_change_output_by",
                // "hamster_set_output_to",
                // "albert_hand_found",
                // "albert_is_oid_value",
                // "albert_value",
                // "albert_move_forward_for_secs",
                // "albert_move_backward_for_secs",
                // "albert_turn_for_secs",
                // "albert_change_both_wheels_by",
                // "albert_set_both_wheels_to",
                // "albert_change_wheel_by",
                // "albert_set_wheel_to",
                // "albert_stop",
                // "albert_set_pad_size_to",
                // "albert_move_to_x_y_on_board",
                // "albert_set_orientation_on_board",
                // "albert_set_eye_to",
                // "albert_clear_eye",
                // "albert_body_led",
                // "albert_front_led",
                // "albert_beep",
                // "albert_change_buzzer_by",
                // "albert_set_buzzer_to",
                // "albert_clear_buzzer",
                // "albert_play_note_for",
                // "albert_rest_for",
                // "albert_change_tempo_by",
                // "albert_set_tempo_to",
                // //sensorBoard
                // "sensorBoard_get_named_sensor_value",
                // "sensorBoard_is_button_pressed",
                // "sensorBoard_led",
                // "sensorBoard_get_number_sensor_value",
                // "sensorBoard_get_digital_value",
                // "sensorBoard_toggle_led",
                // "sensorBoard_toggle_pwm",
                // "sensorBoard_convert_scale",
                // //CODEino
                // "CODEino_get_named_sensor_value",
                // "CODEino_get_sound_status",
                // "CODEino_get_light_status",
                // "CODEino_is_button_pressed",
                // "CODEino_get_accelerometer_direction",
                // "CODEino_get_accelerometer_value",
                // //"CODEino_get_number_sensor_value",
                // "CODEino_get_digital_value",
                // //"CODEino_toggle_led",
                // //"CODEino_toggle_pwm",
                // "CODEino_convert_scale",
                // //2016-09-23
                // "CODEino_get_analog_value",
                // "CODEino_set_digital_value",
                // "CODEino_set_pwm_value",
                // "CODEino_led_by_value",
                // "CODEino_set_rgb_off",
                // "CODEino_set__led_by_rgb",
                // "CODEino_rgb_set_color",
                // "CODEino_set_rgb_value",
                // "CODEino_set_rgb_add_value",
                // //robotis_openCM70
                // "robotis_openCM70_sensor_value",
                // "robotis_openCM70_aux_sensor_value",
                // "robotis_openCM70_cm_buzzer_index",
                // "robotis_openCM70_cm_buzzer_melody",
                // "robotis_openCM70_cm_sound_detected_clear",
                // "robotis_openCM70_cm_led",
                // "robotis_openCM70_cm_motion",
                // "robotis_openCM70_aux_motor_speed",
                // "robotis_openCM70_aux_servo_mode",
                // "robotis_openCM70_aux_servo_speed",
                // "robotis_openCM70_aux_servo_position",
                // "robotis_openCM70_aux_led_module",
                // "robotis_openCM70_aux_custom",
                // "robotis_openCM70_cm_custom_value",
                // "robotis_openCM70_cm_custom",
                // "robotis_carCont_sensor_value",
                // "robotis_carCont_cm_led",
                // "robotis_carCont_cm_sound_detected_clear",
                // "robotis_carCont_aux_motor_speed",
                // "robotis_carCont_aux_motor_speed2",
                // "robotis_carCont_cm_calibration",

                // //XBOT Blocks added
                // "xbot_analogValue",
                // "xbot_digitalInput",
                // "xbot_digitalOutput",
                // "xbot_analogOutput",
                // "xbot_rgb",
                // "xbot_rgb_picker",
                // "xbot_buzzer",
                // "xbot_servo",
                // "xbot_oneWheel",
                // "xbot_twoWheel",
                // "xbot_lcd",
                // //end of XBOT Blocks added
                // // ardublock Added 2016-06-01
                // "ardublock_get_number_sensor_value",
                // "ardublock_get_digital_value",
                // "ardublock_toggle_led",
                // "ardublock_toggle_pwm",
                // "ardublock_convert_scale",
                // // ardublock Added 2016-06-01

                // "ev3_get_sensor_value",
                // "ev3_touch_sensor",
                // "ev3_color_sensor",
                // "ev3_motor_power",
                // "ev3_motor_power_on_time",
                // "ev3_motor_degrees",

                // "roduino_on_block",
                // "roduino_off_block",
                // "roduino_get_analog_value",
                // "roduino_get_digital_value",
                // "roduino_get_color",
                // "roduino_set_digital",
                // "roduino_motor",
                // "roduino_set_color_pin",

                // "schoolkit_on_block",
                // "schoolkit_off_block",
                // "schoolkit_get_input_value",
                // "schoolkit_set_output",
                // "schoolkit_motor",
                // "schoolkit_set_servo_value",

                // // codestar 2016-09-26
                // 'codestar_color_single',
                // 'codestar_3color',
                // 'codestar_vibration',
                // 'codestar_buzzer',
                // 'codestar_buzzer_stop',
                // 'codestar_drive',
                // 'codestar_wheel',
                // 'codestar_light',
                // 'codestar_button',
                // 'codestar_ir',
                // 'codestar_sonar',
                // 'codestar_mic',
                // 'codestar_temperature',

                // //jeil science smartBoard. 2016-11-03
                // //smartBoard
                // "smartBoard_get_named_sensor_value",
                // "smartBoard_is_button_pressed",
                // "smartBoard_set_dc_motor_direction",
                // "smartBoard_set_dc_motor_speed",
                // "smartBoard_set_dc_motor_pwm",
                // "smartBoard_set_servo_port_power",
                // "smartBoard_set_servo_port_pwm",
                // "smartBoard_set_servo_speed",
                // "smartBoard_set_servo_angle",
                // "smartBoard_set_number_eight_pin",
                // "smartBoard_get_number_sensor_value",
                // "smartBoard_get_digital_value",
                // "smartBoard_toggle_led",
                // "smartBoard_toggle_pwm",
                // "smartBoard_convert_scale"
            ]
        }];
    }

    option.initOptions = {
        listEnable: false,
        functionEnable: false,
        sceneEditable: false,
    }

    option.hwCategoryList = ['hw_motor', 'hw_melody', 'hw_sensor', 'hw_led'];

    if (typeof define === 'function' && define.amd) {
        define(function() {
            return option;
        });
    } else if (typeof exports === 'object' && typeof exports.nodeName !== 'string') {
        module.exports = option;
    } else {
        window.entryMiniOption = option;
    }
})();
