export const MODAL_PROGRESS = 'MODAL_PROGRESS';

export const POPUP_SHOW = 'POPUP_SHOW';
export const POPUP_HIDE = 'POPUP_HIDE';
export const PAGE_MOVE = 'PAGE_MOVE';
export const SEARCH_POPUP_ITEMS = 'SEARCH_POPUP_ITEMS';
export const FETCH_POPUP_ITEMS = 'FETCH_POPUP_ITEMS';
export const FETCH_POPUP_SUCCESS = 'FETCH_POPUP_SUCCESS';
export const FETCH_POPUP_FAIL = 'FETCH_POPUP_FAIL';

export const CHANGE_PROJECT_NAME = 'CHANGE_PROJECT_NAME';

export const SAVE_PROJECT = 'SAVE_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const LOAD_PROJECT = 'LOAD_PROJECT';

export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const WS_MODE = 'WORKSPACE_MODE';
export const PROJECT_DATA = 'PROJECT_DATA';
