export const MODAL_PROGRESS = 'MODAL_PROGRESS';

export const POPUP_SHOW = 'POPUP_SHOW';
export const POPUP_HIDE = 'POPUP_HIDE';
export const PAGE_MOVE = 'PAGE_MOVE';
export const FETCH_POPUP_ITEMS = 'FETCH_POPUP_ITEMS';

export const CHANGE_PROJECT_NAME = 'CHANGE_PROJECT_NAME';

export const UPDATE_PROJECT = 'UPDATE_PROJECT';

export const PROJECT_DATA = 'PROJECT_DATA';
